free(): invalid pointer
SIGABRT: abort
PC=0x7f6239403e97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc420049cc0, 0xc420049ce8)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420049c90 sp=0xc420049c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x199e270)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420049cc0 sp=0xc420049c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x199e270)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420049cf8 sp=0xc420049cc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420016370)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420049da0 sp=0xc420049cf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420049e88, 0x410022, 0xc4200162c0)
	<autogenerated>:4 +0x46 fp=0xc420049de0 sp=0xc420049da0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420049e68 sp=0xc420049de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7fff8a2cc7b3, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420049ed8 sp=0xc420049e68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420049f58 sp=0xc420049ed8
main.main()
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420049f88 sp=0xc420049f58
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420049fe0 sp=0xc420049f88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420049fe8 sp=0xc420049fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7fff8a2cb5d0
rcx    0x7f6239403e97
rdx    0x0
rdi    0x2
rsi    0x7fff8a2cb360
rbp    0x7fff8a2cb6d0
rsp    0x7fff8a2cb360
r8     0x0
r9     0x7fff8a2cb360
r10    0x8
r11    0x246
r12    0x7fff8a2cb5d0
r13    0x1000
r14    0x0
r15    0x30
rip    0x7f6239403e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
test_cat (__main__.TestJSH) ... ok
test_cat_stdin (__main__.TestJSH) ... FAIL
test_cd_pwd (__main__.TestJSH) ... ok
test_disabled_doublequotes (__main__.TestJSH) ... FAIL
test_doublequotes (__main__.TestJSH) ... ok
test_echo (__main__.TestJSH) ... ok
test_find (__main__.TestJSH) ... FAIL
test_find_dir (__main__.TestJSH) ... FAIL
test_find_pattern (__main__.TestJSH) ... FAIL
test_globbing (__main__.TestJSH) ... ok
test_globbing_dir (__main__.TestJSH) ... FAIL
test_grep (__main__.TestJSH) ... ok
test_grep_files (__main__.TestJSH) ... ok
test_grep_no_matches (__main__.TestJSH) ... ok
test_grep_re (__main__.TestJSH) ... ok
test_grep_stdin (__main__.TestJSH) ... ok
test_head (__main__.TestJSH) ... ok
test_head_n0 (__main__.TestJSH) ... ok
test_head_n5 (__main__.TestJSH) ... ok
test_head_n50 (__main__.TestJSH) ... ok
test_head_stdin (__main__.TestJSH) ... FAIL
test_input_redirection (__main__.TestJSH) ... FAIL
test_input_redirection_infront (__main__.TestJSH) ... FAIL
test_input_redirection_nospace (__main__.TestJSH) ... FAIL
test_ls (__main__.TestJSH) ... ok
test_ls_dir (__main__.TestJSH) ... ok
test_ls_hidden (__main__.TestJSH) ... ok
test_nested_doublequotes (__main__.TestJSH) ... ok
test_output_redirection (__main__.TestJSH) ... FAIL
test_output_redirection_overwrite (__main__.TestJSH) ... FAIL
test_pipe (__main__.TestJSH) ... ok
test_pipe_chain (__main__.TestJSH) ... ok
test_pipe_exception (__main__.TestJSH) ... ok
test_pwd (__main__.TestJSH) ... ok
test_quote_keyword (__main__.TestJSH) ... ok
test_sed (__main__.TestJSH) ... ok
test_sed_g (__main__.TestJSH) ... ok
test_sed_re (__main__.TestJSH) ... ok
test_sed_separator (__main__.TestJSH) ... FAIL
test_sed_stdin (__main__.TestJSH) ... FAIL
test_semicolon (__main__.TestJSH) ... ok
test_semicolon_chain (__main__.TestJSH) ... ok
test_semicolon_exception (__main__.TestJSH) ... ok
test_singlequotes (__main__.TestJSH) ... FAIL
test_splitting (__main__.TestJSH) ... ok
test_substitution (__main__.TestJSH) ... ok
test_substitution_app (__main__.TestJSH) ... ok
test_substitution_doublequotes (__main__.TestJSH) ... ok
test_substitution_insidearg (__main__.TestJSH) ... ok
test_substitution_keywords (__main__.TestJSH) ... ok
test_substitution_semicolon (__main__.TestJSH) ... ok
test_substitution_splitting (__main__.TestJSH) ... ok
test_substitution_wc_find (__main__.TestJSH) ... FAIL
test_tail (__main__.TestJSH) ... ok
test_tail_n0 (__main__.TestJSH) ... ok
test_tail_n5 (__main__.TestJSH) ... ok
test_tail_n50 (__main__.TestJSH) ... ok
test_tail_stdin (__main__.TestJSH) ... FAIL
test_unsafe_ls (__main__.TestJSH) ... FAIL
test_wc (__main__.TestJSH) ... FAIL
test_wc_files (__main__.TestJSH) ... FAIL
test_wc_l (__main__.TestJSH) ... FAIL
test_wc_m (__main__.TestJSH) ... FAIL
test_wc_stdin (__main__.TestJSH) ... FAIL
test_wc_w (__main__.TestJSH) ... FAIL

======================================================================
FAIL: test_cat_stdin (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 108, in test_cat_stdin
    self.assertEqual(result, ["AAA", "BBB", "AAA"])
AssertionError: Lists differ: [''] != ['AAA', 'BBB', 'AAA']

First differing element 0:
''
'AAA'

Second list contains 2 additional elements.
First extra element 1:
'BBB'

- ['']
+ ['AAA', 'BBB', 'AAA']

======================================================================
FAIL: test_disabled_doublequotes (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 453, in test_disabled_doublequotes
    self.assertEqual(result, "\"\"")
AssertionError: "''" != '""'
- ''
+ ""


======================================================================
FAIL: test_find (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 234, in test_find
    self.assertEqual(result, {"./dir2/subdir/file.txt"})
AssertionError: Items in the first set but not the second:
''
Items in the second set but not the first:
'./dir2/subdir/file.txt'

======================================================================
FAIL: test_find_dir (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 252, in test_find_dir
    "dir1/longfile.txt"})
AssertionError: Items in the first set but not the second:
''
Items in the second set but not the first:
'dir1/file1.txt'
'dir1/file2.txt'
'dir1/longfile.txt'

======================================================================
FAIL: test_find_pattern (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 244, in test_find_pattern
    "./dir1/longfile.txt"})
AssertionError: Items in the first set but not the second:
''
Items in the second set but not the first:
'./dir1/longfile.txt'
'./dir1/file1.txt'
'./test.txt'
'./dir1/file2.txt'
'./dir2/subdir/file.txt'

======================================================================
FAIL: test_globbing_dir (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 332, in test_globbing_dir
    self.assertEqual(result, {"dir1/file1.txt", "dir1/file2.txt", "dir1/longfile.txt"})
AssertionError: Items in the first set but not the second:
'dir1/*.txt'
Items in the second set but not the first:
'dir1/file1.txt'
'dir1/file2.txt'
'dir1/longfile.txt'

======================================================================
FAIL: test_head_stdin (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 120, in test_head_stdin
    self.assertEqual(result, [str(i) for i in range(1,11)])
AssertionError: Lists differ: [''] != ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

First differing element 0:
''
'1'

Second list contains 9 additional elements.
First extra element 1:
'2'

- ['']
+ ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

======================================================================
FAIL: test_input_redirection (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 294, in test_input_redirection
    self.assertEqual(result, "CCC")
AssertionError: '' != 'CCC'
+ CCC

======================================================================
FAIL: test_input_redirection_infront (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 300, in test_input_redirection_infront
    self.assertEqual(result, "CCC")
AssertionError: '' != 'CCC'
+ CCC

======================================================================
FAIL: test_input_redirection_nospace (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 306, in test_input_redirection_nospace
    self.assertEqual(result, "CCC")
AssertionError: '' != 'CCC'
+ CCC

======================================================================
FAIL: test_output_redirection (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 313, in test_output_redirection
    self.assertEqual(result, "foo")
AssertionError: '' != 'foo'
+ foo

======================================================================
FAIL: test_output_redirection_overwrite (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 320, in test_output_redirection_overwrite
    self.assertEqual(result, "foo")
AssertionError: "''" != 'foo'
- ''
+ foo


======================================================================
FAIL: test_sed_separator (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 216, in test_sed_separator
    self.assertEqual(result, ["DAA", "BBB", "DAA"])
AssertionError: Lists differ: [''] != ['DAA', 'BBB', 'DAA']

First differing element 0:
''
'DAA'

Second list contains 2 additional elements.
First extra element 1:
'BBB'

- ['']
+ ['DAA', 'BBB', 'DAA']

======================================================================
FAIL: test_sed_stdin (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 210, in test_sed_stdin
    self.assertEqual(result, ["DAA", "BBB", "DAA"])
AssertionError: Lists differ: [''] != ['DAA', 'BBB', 'DAA']

First differing element 0:
''
'DAA'

Second list contains 2 additional elements.
First extra element 1:
'BBB'

- ['']
+ ['DAA', 'BBB', 'DAA']

======================================================================
FAIL: test_singlequotes (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 423, in test_singlequotes
    self.assertEqual(result, "a  b")
AssertionError: 'a   b' != 'a  b'
- a   b
?  -
+ a  b


======================================================================
FAIL: test_substitution_wc_find (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 399, in test_substitution_wc_find
    self.assertEqual(result, "26")
AssertionError: '' != '26'
+ 26

======================================================================
FAIL: test_tail_stdin (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 150, in test_tail_stdin
    self.assertEqual(result, [str(i) for i in range(11,21)])
AssertionError: Lists differ: [''] != ['11', '12', '13', '14', '15', '16', '17', '18', '19', '20']

First differing element 0:
''
'11'

Second list contains 9 additional elements.
First extra element 1:
'12'

- ['']
+ ['11', '12', '13', '14', '15', '16', '17', '18', '19', '20']

======================================================================
FAIL: test_unsafe_ls (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 357, in test_unsafe_ls
    self.assertEqual(result, "AAA")
AssertionError: '' != 'AAA'
+ AAA

======================================================================
FAIL: test_wc (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 258, in test_wc
    self.assertEqual(result, ["3", "3", "12"])
AssertionError: Lists differ: [] != ['3', '3', '12']

Second list contains 3 additional elements.
First extra element 0:
'3'

- []
+ ['3', '3', '12']

======================================================================
FAIL: test_wc_files (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 288, in test_wc_files
    self.assertEqual(result, "4")
AssertionError: '' != '4'
+ 4

======================================================================
FAIL: test_wc_l (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 282, in test_wc_l
    self.assertEqual(result, "3")
AssertionError: '' != '3'
+ 3

======================================================================
FAIL: test_wc_m (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 270, in test_wc_m
    self.assertEqual(result, "12")
AssertionError: '' != '12'
+ 12

======================================================================
FAIL: test_wc_stdin (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 264, in test_wc_stdin
    self.assertEqual(result, ["3", "3", "12"])
AssertionError: Lists differ: [] != ['3', '3', '12']

Second list contains 3 additional elements.
First extra element 0:
'3'

- []
+ ['3', '3', '12']

======================================================================
FAIL: test_wc_w (__main__.TestJSH)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 276, in test_wc_w
    self.assertEqual(result, "3")
AssertionError: '' != '3'
+ 3

----------------------------------------------------------------------
Ran 65 tests in 435.975s

FAILED (failures=24)
